controller:
  admin:
    username: admin
    existingSecret: "jenkins-admin-secret"
    existingSecretPasswordKey: "password"

  serviceType: LoadBalancer
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

  persistence:
    enabled: true
    storageClass: "standard"
    size: 20Gi
    accessMode: ReadWriteOnce

  installPlugins:
    - kubernetes:4155.v9611f016f5c3
    - workflow-aggregator:596.v8c21c963d92d
    - configuration-as-code:1777.v39e083f1ef68
    - credentials-binding:665.v3f956f081442
    - git:5.2.1
    - github:1.37.3
    - dark-theme:latest