controller:
  # 1. Identity & Security
  admin:
    username: admin
    existingSecret: "jenkins-admin-secret"
    existingSecretPasswordKey: "password"

  # 2. Access (Exposing Jenkins to the Internet)
  serviceType: LoadBalancer
  service:
    port: 80
    targetPort: 8080

  # 3. Resources
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "800m"
      memory: "1200Mi"
  javaOpts: "-Xms512m -Xmx1024m -Djenkins.install.runSetupWizard=false"

  # 4. Storage (Persistence)
  persistence:
    enabled: true
    storageClass: "ebs-sc" 
    size: 10Gi
    accessMode: ReadWriteOnce

  # 5. Mandatory Plugins for Pipeline
  installPlugins:
    - kubernetes
    - git:5.2.1
    - workflow-aggregator:596.v8c21c963d92d
    - configuration-as-code:1932.v75cb_b_f1b_698d
    - credentials-binding:687.v619cb_15e923f
    
  # 6. Health Checks (ВИПРАВЛЕНО ВІДСТУПИ)
  readinessProbe:
    failureThreshold: 10
    httpGet:
      path: /login
      port: http
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15 
  livenessProbe:
    failureThreshold: 10
    httpGet:
      path: /login
      port: http
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 15