pipeline {
  agent {
    kubernetes {
      yaml '''
  apiVersion: v1
  kind: Pod
  spec:
    containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["99d"]
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
    - name: git
      image: alpine/git
      command: ["sleep"]
      args: ["99d"]
    volumes:
    - name: docker-config
      secret:
        secretName: regcred
        items:
        - key: .dockerconfigjson
          path: config.json
  '''
    }
  }

  environment {
    REGISTRY = "829703038395.dkr.ecr.eu-west-1.amazonaws.com"
    REPO_NAME = "lesson-8-9-ecr"
    IMAGE_TAG = "${env.BUILD_NUMBER}"
    GIT_REPO = "https://github.com/dm-zhuk/goit-devops-hw-03.git"
  }

  stages {
    stage('Checkout') {
      steps {
        container('git') {
          sh '''
            rm -rf repo || true   # clean if previous run left something
            git clone ${GIT_REPO} repo
            cd repo
            git checkout lesson-8-9
          '''
        }
      }
    }

    stage('Build & Push') {
      steps {
        container('kaniko') {
          sh '''
            cd repo/lesson-8-9
            /kaniko/executor \
              --context `pwd` \
              --dockerfile Dockerfile \
              --destination ${REGISTRY}/${REPO_NAME}:${IMAGE_TAG} \
              --destination ${REGISTRY}/${REPO_NAME}:latest \
              --cache=true
          '''
        }
      }
    }

    stage('Update Helm values & Push') {
      steps {
        container('git') {
          withCredentials([usernamePassword(
            credentialsId: 'github-pat',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
          )]) {
            sh """
              cd repo
              git config user.email "jenkins@ci"
              git config user.name "Jenkins CI"
              git remote set-url origin https://${GIT_USER}:${GIT_TOKEN}@github.com/dm-zhuk/goit-devops-hw-03.git
              git checkout lesson-8-9
              git pull origin lesson-8-9 --rebase
              
              # Update tag
              echo "Current values.yaml:"
              cat lesson-8-9/charts/django-app/values.yaml
              sed -i 's/tag: \".*\"/tag: \"${IMAGE_TAG}\"/' lesson-8-9/charts/django-app/values.yaml
              echo "Updated values.yaml:"
              cat lesson-8-9/charts/django-app/values.yaml

              git add lesson-8-9/charts/django-app/values.yaml
              git commit -m "Jenkins build ${BUILD_NUMBER}: update image tag to ${IMAGE_TAG} [ci skip]" || echo "No changes to commit"
              git push origin lesson-8-9
            """
          }
        }
      }
    }
  }
}