pipeline {
  agent {
    kubernetes {
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.16.0-debug
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["infinity"]
  - name: git
    image: alpine/git
    command: ["sleep"]
    args: ["infinity"]
'''
    }
  }

  environment {
    REGISTRY = "829703038395.dkr.ecr.eu-west-1.amazonaws.com"
    REPO_NAME = "lesson-8-9-ecr"
    IMAGE_TAG = "${env.BUILD_NUMBER}"
    GIT_REPO = "https://github.com/dm-zhuk/goit-devops-hw-03.git"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm // Use Jenkins native checkout for the current repo/branch
      }
    }

    stage('Build & Push') {
  steps {
    container('kaniko') {
      sh """
        /kaniko/executor \
          --context ./ \
          --dockerfile Dockerfile \
          --destination ${REGISTRY}/${REPO_NAME}:${IMAGE_TAG} \
          --destination ${REGISTRY}/${REPO_NAME}:latest \
          --cache=true
      """
    }
  }
}

    stage('Update Helm values & Push') {
      steps {
        container('git') {
          withCredentials([usernamePassword(
            credentialsId: 'github-pat',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
          )]) {
            sh '''
              git config user.email "jenkins@ci"
              git config user.name "Jenkins CI"
              # Re-auth the origin to allow pushing
              git remote set-url origin https://${GIT_USER}:${GIT_TOKEN}@github.com/dm-zhuk/goit-devops-hw-03.git
              git pull origin lesson-8-9 --rebase
              
              # Update the tag in your chart
              sed -i "s|tag: .*|tag: \\"${IMAGE_TAG}\\"|" charts/django-app/values.yaml
              
              git add charts/django-app/values.yaml
              git commit -m "Jenkins: update image tag to ${IMAGE_TAG} [ci skip]" || echo "No changes to commit"
              git push origin lesson-8-9
            '''
          }
        }
      }
    }
  }
}