apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dm-zhuk/goit-devops-hw-03.git
    targetRevision: lesson-8-9
    path: lesson-8-9/charts/django-app
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true      # Removes resources that are no longer in Git
      selfHeal: true   # Corrects drift if someone manually edits K8s resources
    syncOptions:
      - CreateNamespace=true # Creates 'default' if it doesn't exist