replicaCount: 2

image:
  repository: "829703038395.dkr.ecr.eu-west-1.amazonaws.com/final-project-ecr"
  tag: "latest"
  pullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

django:
  secretKey: "your-very-secure-secret-key-here"

# Налаштування додатка (актуальні Endpoint)
dbUrl: "postgres://db_user:pass02Word2027@final-project-db.cluster-c7m2is6is8u4.eu-west-1.rds.amazonaws.com:5432/django_db"
allowedHosts: "*"

# Ресурси (важливо для стабільності на t3.micro)
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi