image:
  repository: 829703038395.dkr.ecr.eu-west-1.amazonaws.com/lesson-8-9-ecr
  tag: '45'
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DEBUG: "false"
  ALLOWED_HOSTS: "a2eb0bbdffc04416ca9cd37341ae0e85-1536671044.eu-west-1.elb.amazonaws.com,localhost,127.0.0.1"

secretEnv:
  SECRET_KEY: "7-msDOwMQmZhI9hncT9pRdpUoDrgu4dhhjFc7CvNkGdU1-i5QYYF_NgsThRiI9-_0yA"
  DATABASE_URL: "postgres://admin:pass7890@my-postgres-postgresql:5432/django_db"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"