apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-secrets
type: Opaque
data:
  # Значення має бути в base64. Helm зробить це автоматично з values.
  SECRET_KEY: {{ .Values.django.secretKey | b64enc | quote }}