# Deploys Django pods, uses ConfigMap for env.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.hpa.minReplicas }}
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000  # Django default
        envFrom:
          - secretRef:
              name: {{ include "django-app.fullname" . }}-secret
          - configMapRef:
              name: {{ include "django-app.fullname" . }}-config
        - configMapRef:
            name: {{ .Release.Name }}-config
        - secretRef:
            name: {{ .Release.Name }}-django-secret
        resources: {{ toYaml .Values.resources | nindent 10 }}