apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretEnv.SECRET_KEY | quote }}
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}