# LoadBalancer service — exposes public IP for access.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 8000 }}
    protocol: TCP
  selector:
    app: django-app